# This file contains the configuration for the dev environment.
# None of the values here are actually secret, so it's fine
# to commit this file to the repository.
server:
  ip: "127.0.0.1"
  port: 8000
session:
  ttl: 24 hours
database:
  database_path: "./demo_sessions.db"
